import { Category, Contest, ContestStatus } from './types';

export const MOCK_CONTESTS: Contest[] = [
  {
    id: '1',
    title: 'Ristrutturazione Appartamento Centro Storico',
    location: 'Palermo, Sicilia',
    category: Category.INTERIOR,
    budget: 1500,
    proposalsCount: 12,
    deadline: '2025-01-15',
    daysRemaining: 5,
    status: ContestStatus.OPEN,
    imageUrl: 'https://picsum.photos/800/600?random=1',
    description: 'Cerchiamo un design moderno che rispetti le origini storiche dell\'immobile.',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Micro-Living Milano',
    location: 'Milano, Lombardia',
    category: Category.RESIDENTIAL,
    budget: 800,
    proposalsCount: 8,
    deadline: '2025-01-20',
    daysRemaining: 12,
    status: ContestStatus.OPEN,
    imageUrl: 'https://picsum.photos/800/600?random=2',
    description: 'Ottimizzazione spazi per un monolocale di 35mq in zona Navigli.',
  },
  {
    id: '3',
    title: 'Concept Boutique Hotel',
    location: 'Costiera Amalfitana',
    category: Category.COMMERCIAL,
    budget: 3000,
    proposalsCount: 25,
    deadline: '2025-01-12',
    daysRemaining: 3,
    status: ContestStatus.OPEN,
    imageUrl: 'https://picsum.photos/800/600?random=3',
    description: 'Progettazione preliminare per la conversione di una villa storica.',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Giardino Pensile Uffici',
    location: 'Torino',
    category: Category.URBAN,
    budget: 1200,
    proposalsCount: 5,
    deadline: '2025-02-01',
    daysRemaining: 20,
    status: ContestStatus.OPEN,
    imageUrl: 'https://picsum.photos/800/600?random=4',
    description: 'Area relax verde per dipendenti tech company.',
  }
];
